# Generated by Django 3.2.11 on 2022-09-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='firstName',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='resume',
            name='lastName',
            field=models.CharField(default='', max_length=30),
        ),
    ]
